# 
# Global 
#
startDate : "2021-06-08"
morning   : "09:00-12:30"
afternoon : "13:30-17:00"
course_id : "Boerhaave_202106"
course_path : "Boerhaave_202106"
course_label : "LUMC/Boerhaave, Jun2021: Using R for data analysis"

#
# slots   : slot+
# slot    : lecture+
# lecture : "<file-basename>:<title>:<has_tasks>:<minutes>"
#
slots:
  slot1:
    slot_label: "R and RStudio basics"
    slot_date:
    slot_time: "09:00-12:30"
    lectures:
      - "index:Course Introduction:FALSE:15"
      - "introduction0:R Introduction:FALSE:10"
      - "basic_calculator0:Calculator:TRUE:25"
      - "basic_variables0:Variables:TRUE:30"
      - "course_data0:Example data (pulse, survey):FALSE:10" 
      - "basic_projects0:Projects:FALSE:20" 
      - "basic_scripts0:Scripts:FALSE:60" 
  slot2:
    slot_label : "Data structures 1/2"
    slot_date:
    slot_time: "13:30-17:00"
    lectures:
      - "basic_vectors0:Vectors:TRUE:30"
      - "basic_factors0:Factors:TRUE:60"
      - "packages0:Install/use packages:FALSE:30"
  slot3:
      slot_label : "Data manipulation 1/3"
      slot_date :
      slot_time : "09:00-12:30"
      lectures:
        - "tidyverse0:Tidyverse library:FALSE:45"
        - "dplyr_tibble0:Tibble:TRUE:30"
        - "dplyr_select0:Select variables/cols:TRUE:30"
        - "dplyr_filter0:Filter observations/rows:TRUE:30"
        - "dplyr_mutate0:Add/modify variables:TRUE:30"
  slot4:
    slot_label : "Data manipulation 2/3"
    slot_date :
    slot_time : "13:30-17:00"
    lectures:
      - "dplyr_pipe0:Pipe operator:TRUE:45"
      - "dplyr_summarise0:Summarise:TRUE:30"
      - "dplyr_group0:Groups:TRUE:30"
  slot5:
    slot_label : "Data structures 2/2"
    slot_date :
    slot_time : "09:00-12:30"
    lectures:
      - "basic_lists0:Lists:TRUE:45"
      - "basic_formulas0:Formulas:TRUE:30"
      - "basic_matrices0:Matrices:TRUE:30"
  slot6:
    slot_label : "Graphics"
    slot_date :
    slot_time : "13:30-17:00"
    lectures:
      - "ggplot_basics0:Plots/ggplot2:TRUE:45"
      - "ggplot_scales0:Plot axes/scales:TRUE:30"
      - "ggplot_facets_themes0:Plot panels/facets:TRUE:30"
      - "ggplot_geoms0:Plot types:FALSE:30"
  slot7:
    slot_label : "Data manipulation 3/3 and functions"
    slot_date :
    slot_time : "09:00-12:30"
    lectures:
      - "dplyr_join0:Merging/joining tables:TRUE:45"
      - "tidyr_reshape0:Reshaping tables:TRUE:30"
      - "advanced_user_functions0:User-defined functions:TRUE:30"
      - "useful_functions0:Useful R functions:FALSE:30"
  slot8:
    slot_label : "Self-study assignment"
    slot_date :
    slot_time : "13:30-17:00"
    lectures:
  
# 
# materials : material+
# material  : id:label:path:out_path "<id>:<label>:<>:<minutes>"
materials:
  - "pulse:Pulse dataset, CSV format:data/pulse.csv:data/pulse.csv"
  - "survey:Survey dataset, CSV format:data/survey.csv:data/survey.csv"
  - "exProjDir:RStudio project directory example:materials/RStudio_Project_Dir_Example.zip:materials/RStudio_Project_Dir_Example.zip"
  
