---
title : "Course recent history"
---

### as part of CRiP: Sep. 27th-Oct. 15th, 2019

The primary source for dates/times/rooms is the CRiP web page.
- update date: 2019-09-23

| Date | Time | Room | Teachers | Slot |
| --- | --- | --- | --- | --- |
| 27-09-2019 | 09.30-12.30 | CZ-6 | Jelle, Szymon | slot 1 |
| 02-10-2019 | 08.30-12.30 | CZ-3 | Szymon, Ramin | slot 2 |
| 04-10-2019 | 13.30-17.30 | CZ-3 | Jelle | slot 3 |
| 08-10-2019 | 09.00-17.00 | V4-18/22 | Ramin, Szymon | slot 4, 5 |
| 10-10-2019| 13.30-17.30 | V4-18/22 | Szymon, Ramin | slot 6 |
| 11-10-2019 | 13.30-17.30 | CZ-6 | Ramin, Szymon | slot 7 |
| 15-10-2019 | 14.00-16.00 | V4-18/22 | - | exam |

### as part of "Introduction Bioinformatics": Sep. 12th --- 19th, 2019

| Date | Time | Room | Teacher | Slot |
| --- | --- | --- | --- | --- |
| 12-09-2019 | 09:00-12:00 | V2-34 | ? | slot 1 |
| 12-09-2019 | 13:00-16:00 | CZ-6  | ? | slot 2 |
| 13-09-2019 | 09:00-12:00 | J1-83 | ? | slot 3 |
| 13-09-2019 | 13:00-16:00 | J1-83 | ? | slot 4 |
| 16-09-2019 | 09:00-12:00 | J1-83 | ? | slot 5 |
| 16-09-2019 | 13:00-16:00 | J1-83 | ? | slot 6 |
| 17-09-2019 | 09:00-12:00 | J1-83 | ? | slot 7 |
| 17-09-2019 | 13:00-16:00 | J1-83 | ? | slot 8 |
| 19-09-2019 | 15:00-17:00 | V2-34 | ? | exam |

### LUMC Boerhaave Nascholing: June 4th -- 7th, 2019

| Date | Time | Room | Teacher(s) | Slot |
| --- | --- | --- | --- | --- |
| 04-06-2019 | 09.00-12.30 | J1-83 | Jelle | slot 1 |
| 04-06-2019 | 13.30-17.00 | J1-83 | Szymon | slot 2 |
| 05-06-2019 | 09.00-12.30 | J1-83 | Renee | slot 3 |
| 05-06-2019 | 13.30-17.00 | J1-83 | Szymon | slot 4 |
| 06-06-2019 | 09.00-12.30 | J1-83 | Ramin | slot 5 |
| 06-06-2019 | 13.30-17.00 | J1-83 | Szymon | slot 6 |
| 07-06-2019 | 09.00-12.30 | J1-83 | Ramin | slot 7 |
| 07-06-2019 | 13.30-17.00 | J1-83 | ? | slot 8/exam |

The course will take place in LUMC, building 1 (main building).

Other info: https://www.boerhaavenascholing.nl/medische-nascholing/2019/using-r-for-data-analysis-2019/

### VU edition: Jan. 28th --- Feb. 1st, 2019

| Date | Time | Room | Teachers | Slot |
| --- | --- | --- | --- | --- |
| 28-01-2019 | 09.00-12.30 | De Waver | Szymon | slot 1 |
| 28-01-2019 | 13.30-17.00 | De Waver | Jelle | slot 2 |
| 29-01-2019 | 09.00-12.30 | De Waver | Renee | slot 3 |
| 29-01-2019 | 13.30-17.00 | De Waver | Ramin | slot 4 |
| 31-01-2019 | 09.00-12.30 | De Waver | Ramin | slot 5 |
| 31-01-2019 | 13.30-17.00 | De Waver | Szymon | slot 6 |
| 01-02-2019 | 09.00-12.30 | De Waver | Ramin | slot 7 |
| 01-02-2019 | 13.30-17.00 | De Waver | Renee | slot 8 |

Possibly outdated 2018 info: http://www.bigstatistics.nl/teaching/

The rooms are located at VUmc.

### as associated with CRiP: Sep. 28th-Oct. 16th, 2018

The primary source for dates/times/rooms is:

- https://www.lumc.nl/org/onderwijsrooster/coordinatoren/universitaire-opleidingen/
- section "Roosteroverzicht Biomedische Wetenschappen 2018-2019"
- course id: "CRIP-R"
- update date: 2018-08-23

| Date | Time | Room | Teachers | Slot |
| --- | --- | --- | --- | --- |
| 28-09-2018 | 09.30-12.30 | ? | Jelle | slot 1 |
| 04-10-2018 | 08.30-12.30 | J1-117_(route-554) | Ramin | slot 2 |
| 05-10-2018 | 13.30-17.30 | V4-18/22 | Jelle | slot 3 |
| 09-10-2018 | 09.00-11.30 | CZ-1_route-768 | Ramin | slot 4 |
| 09-10-2018 | 12.30-17.00 | CZ-1_route-768 | Ramin | slot 5 |
| 11-10-2018 | 13.30-17.30 | CZ-3 | Dani | slot 6 |
| 12-10-2018 | 13.30-17.30 | V2-18/22 | Ramin | slot 7 |
| 16-10-2018 | 14.30-16.30 | CZ-5_route-558 | Ramin | exam |
<!-- | 16-10-2018 | 14.15-17.30 | CZ-5_route-558 | Ramin | slot 8 | -->

The course will take place in LUMC.

### as part of "Introduction Bioinformatics": Sep. 20th --- 27th, 2018

For this course there might still be free places. Please contact Madeleine Nivard (`M.J.M.Nivard at lumc.nl`) to check.

The primary source for dates/times/rooms is:

- https://www.lumc.nl/org/onderwijsrooster/coordinatoren/universitaire-opleidingen/
- section "Roosteroverzicht Geneeskunde 2018-2019"
- course id: "G3-M23-1"
- update date: 2018-08-23

| Date | Time | Room | Teacher | Slot |
| --- | --- | --- | --- | --- |
| 20-09-2018 | 09:00-12:00 | B1-81_(route-15) | Jelle | slot 1 |
| 20-09-2018 | 13:00-16:00 | B1-81_(route-15) | Dani/Ramin/Szymon | slot 2 |
| 21-09-2018 | 09:00-12:00 | CZ-2_route-766 | Jelle | slot 3 |
| 21-09-2018 | 13:00-16:00 | V4-50 | Ramin | slot 4 |
| 24-09-2018 | 09:00-12:00 | J1-83_(route-555) | ??? | slot 5 |
| 24-09-2018 | 13:00-16:00 | V4-50 | ??? | slot 6 |
| 25-09-2018 | 09:00-12:00 | V4-18/22 | ??? | slot 7 |
| 25-09-2018 | 13:00-16:00 | CZ-2 | ??? | slot 8 |
| 27-09-2018 | 15:00-17:00 | CZ-3 | ??? | exam |

### LUMC Boerhaave Nascholing: June 4th-7th, 2018

| Date | Time | Room | Teacher(s) | Slot |
| --- | --- | --- | --- | --- |
| 04-06-2018 | 09.00-12.30 | J1-83 | Jelle | slot 1 |
| 04-06-2018 | 13.30-17.00 | J1-83 | Szymon | slot 2 |
| 05-06-2018 | 09.00-12.30 | J1-83 | Renee | slot 3 |
| 05-06-2018 | 13.30-17.00 | J1-83 | Ramin | slot 4 |
| 06-06-2018 | 09.00-12.30 | J1-83 | Renee | slot 5 |
| 06-06-2018 | 13.30-17.00 | J1-83 | Szymon | slot 6 |
| 07-06-2018 | 09.00-12.30 | J1-83 | Jelle | slot 7 |
| 07-06-2018 | 13.30-17.00 | J1-83 | Ramin | slot 8 |

The course took place in LUMC, building 1 (main building).

Other info: https://www.boerhaavenascholing.nl/medische-nascholing/2018/using-r-for-data-analysis/

### VU edition: Feb. 12th --- 15th, 2018

More info: http://www.bigstatistics.nl/teaching/

| Date | Time | Room | Teachers | Slot |
| --- | --- | --- | --- | --- |
| 12-02-2018 | 09.00-12.30 | Leidseplein (198) | Jelle (Armin) | slot 1 |
| 12-02-2018 | 13.30-17.00 | Leidseplein (198) | Szymon | slot 2 |
| 13-02-2018 | 09.00-12.30 | Nieuwmarkt (202) | Ramin | slot 3 |
| 13-02-2018 | 13.30-17.00 | Nieuwmarkt (202) | Renee | slot 4 |
| 14-02-2018 | 09.00-12.30 | Leidseplein (198) | Renee | slot 5 |
| 14-02-2018 | 13.30-17.00 | Leidseplein (198) | Szymon | slot 6 |
| 15-02-2018 | 09.00-12.30 | De Dam (206) | Jelle (Armin) | slot 7 |
| 15-02-2018 | 13.30-17.00 | De Dam (206) | Ramin (Armin) | slot 8/exam |

The rooms are located at VUmc, Polyclinic building, 6th floor, aisle X (PK 6X).

### as associated with CRiP: Sep. 29th, 2017 and Oct. 5th --- 17th, 2017

| Date | Time | Room | Teachers | Slot |
| --- | --- | --- | --- | --- |
| 29-09-2017 | 09.30-12.30 | CZ-5 | Jelle, Szymon, Nikos, Dani, Diaa | slot 1 |
| 05-10-2017 | 08.30-12.30 | V4-18/22 | Szymon, Ramin | slot 2 |
| ~~06-10-2017~~ | ~~09.00-13.00~~ | ~~J1-83 (route-555)~~ |  |  |
| 06-10-2017 | 13.00-15.00 | J1-83 (route-555) | Jelle, Diaa | slot 3 |
| 06-10-2017 | 15.00-17.00 | V4-50 | Jelle, Diaa | slot 3 |
| 10-10-2017 | 09.00-13.00 | V2-18/22 | Ramin, Szymon | slot 4 |
| 10-10-2017 | 13.00-17.00 | V2-18/22 | Ramin, Szymon | slot 5(6) |
| 12-10-2017 | 13.30-17.30 | V2-34 | Szymon, Ramin | slot 6(5) |
| 13-10-2017 | 13.30-17.30 | V3-36 | Jelle, Diaa | slot 7 |
| 17-10-2017 | 13.30-17.30 | V4-62 | Jelle, Ramin | slot 8/exam |

Additional teaching support: Nikos Pappas, Dani Borras, Diaa al Mohamad.

### as part of "Introduction Bioinformatics": Sep. 7th --- 11th, 2017

| Date | Time | Room | Teacher | Slot |
| --- | --- | --- | --- | --- |
| 07-09-2017 | 09:30-12:45 | J1-84 | Ramin | slot 1 |
| 07-09-2017 | 13:45-17:00 | J1-84 | Szymon | slot 2 |
| 08-09-2017 | 09:30-12:45 | J1-84 | Jelle | slot 3 |
| 08-09-2017 | 13:45-17:00 | J1-84 | Ramin | slot 4 |
| 11-09-2017 | 09:30-12:45 | J1-84 | Jelle | slot 5 |
| 11-09-2017 | 13:45-17:00 | J1-84 | Szymon | slot 6 |

The course took place in LUMC building 1, room __J1-84__.
In this course iteration slot 7 and slot 8 were not presented.


### organized by "Boerhaave Nascholing": June 13th, 2017 --- June 16th, 2017

The course was divided into 8 slots, 2 slots per day:

- __09:30__-__12:45__ (the morning slot)
- __13:45__-__17:00__ (the afternoon slot)

The course took place in LUMC, room __J1-83__.
