#
# Global
#
startDate : "2024-01-16"
course_id : "HLO_202301"
course_label : "Introduction to R | HLO"
index_file : "S01L01l_index.html"

#
# slots   : slot+
# slot    : lecture+
# lecture : "<file-basename>:<title>:<has_tasks>:<minutes>"
#

slots:
  slot1:
    slot_label: "R and RStudio basics"
    slot_date: 0
    slot_time: "11:15-14:45"
    slot_plan: "l45:b10:l35:b30:l90"
    lectures:
      - "index:Course Introduction:FALSE:5"
      - "introduction0:R Introduction:FALSE:10"
      - "basic_calculator0:Calculator:TRUE:15"
      - "basic_variables0:Variables:TRUE:15"
      - "tidyverse0:Tidyverse library:FALSE:10"
      - "course_data0:Example data (pulse, survey):FALSE:5"
      - "basic_projects0:Projects:FALSE:20"
      - "basic_scripts0:Scripts:FALSE:35"
      - "basic_vectors0:Vectors (introduction):TRUE:35"
      - "basic_vectors0a|basic_vectors0.Rmd:Vectors (practicing):TRUE:20"

  slot2:
    slot_label : "Data manipulation (1/2)"
    slot_date: 10
    slot_time: "09:30-12:30"
    slot_plan: "l50:b10:l50:b10:l60"
    lectures:
      - "dplyr_tibble0:Tibble:TRUE:50"
      - "dplyr_select0:Select variables/cols:TRUE:50"
      - "dplyr_filter0:Filter observations/rows:TRUE:60"

  slot3:
    slot_label : "Data manipulation (2/2)"
    slot_date: 20
    slot_time: "09:30-12:30"
    slot_plan: "l75:b15:l90"
    lectures:
      - "dplyr_mutate0:Add/modify variables:TRUE:45"
      - "dplyr_pipe0:Pipe operator:TRUE:30"
      - "dplyr_summarise0:Summarise:TRUE:45"
      - "dplyr_group0:Groups:TRUE:45"
  slot4:
    slot_label : "Graphics - Lists and Factors - SSA handout"
    slot_date: 21
    slot_time: "09:15-12:30"
    slot_plan: "l60:b5:l30:b5:l40:b5:l50"
    lectures:
      - "ggplot_basics0:Plots/ggplot2:TRUE:30"
      - "ggplot_scales0:Plot axes/scales:TRUE:30"
      - "ggplot_facets_themes0:Plot panels/facets/size:TRUE:30"
      - "basic_lists0:Lists:TRUE:40"
      - "basic_factors0:Factors:TRUE:40"
      - "ed0:Q&A:FALSE:10"
      
  slot5:
    slot_label: "Exam"
    slot_date: 30
    slot_time: "13:30-16:30"
    slot_plan: "l180"
    lectures:
      - "ed1:Exam:FALSE:180"

#
# materials : material+
# material  : id:label:path:out_path "<id>:<label>:<>:<minutes>"
materials:
  - "pulse:Pulse dataset, CSV format:data/pulse.csv:data/pulse.csv"
  - "survey:Survey dataset, CSV format:data/survey.csv:data/survey.csv"
  - "exProjDir:RStudio project directory example:materials/RStudio_Project_Dir_Example.zip:materials/RStudio_Project_Dir_Example.zip"
  - "Self-study assignment (SSA) :materials/SSA_HLO2024.zip:materials/SSA_HLO2024.zip"
  - "Self-study assignment (SSA) solutions :materials/SSA_HLO2024_solutions.zip:materials/SSA_HLO2024_solutions.zip"

  # - "airports:Airports dataset (nycflights13), CSV format:data/airports.csv:data/airports.csv"
  # - "flights:Flights dataset (nycflights13), CSV format:data/flights.csv:data/flights.csv"
  # - "nycflights13:Flights and Airports dataset (nycflights13), zipped CSV files:materials/nycflights13_tables.zip:materials/nycflights13_tables.zip"

