#
# Global
#
startDate : "2021-09-27"
course_id : "CRiP_202109"
course_label : "CRiP, Sep2021: Using R for data analysis"
index_file : "S01L01l_index.html"
#
# slots   : slot+
# slot    : lecture+
# lecture : "<file-basename>:<title>:<has_tasks>:<minutes>"
#
slots:
  slot1:
    slot_label: "R and RStudio basics; R Markdown"
    slot_date: 0
    slot_time: "13:15-17:00"
    slot_plan: "l45:b15:l45:b30:l90"
    lectures:
      - "index:Course Introduction:FALSE:15"
      - "introduction0:R Introduction:FALSE:15"
      - "basic_calculator0:Calculator:TRUE:15"
      - "basic_variables0:Variables:TRUE:30"
      - "packages0:Install/use packages:FALSE:15"
      - "course_data0:Example data (pulse, survey):FALSE:10"
      - "basic_projects0:Projects:FALSE:20"
      - "basic_scripts0:Scripts (R Markdown):FALSE:60"
  slot2:
    slot_label : "Data structures 1/2"
    slot_date: 1
    slot_time: "09:00-12:00"
    slot_plan: "l90:b30:l60"
    lectures:
      - "basic_vectors0:Vectors:TRUE:75"
      - "useful_functions0:Useful R functions:FALSE:15"
      - "basic_factors0:Factors:TRUE:60"
  slot3:
    slot_label : "Data manipulation 1/3"
    slot_date : 1
    slot_time : "13:15-17:00"
    lectures:
      - "tidyverse0:Tidyverse library:FALSE:15"
      - "dplyr_tibble0:Tibble:TRUE:45"
      - "dplyr_select0:Select variables/cols:TRUE:45"
      - "dplyr_filter0:Filter observations/rows:TRUE:45"
      - "dplyr_mutate0:Add/modify variables:TRUE:30"
  slot4:
    slot_label : "Data manipulation 2/3"
    slot_date : 2
    slot_time : "09:00-12:00"
    lectures:
      - "dplyr_pipe0:Pipe operator:TRUE:60"
      - "dplyr_summarise0:Summarise:TRUE:60"
      - "dplyr_group0:Groups:TRUE:60"
  slot5:
    slot_label : "Data structures 2/2, flow control"
    slot_date : 2
    slot_time : "13:15-17:00"
    slot_plan: "l45:b15:l45:b15:l45:b15:l45"
    lectures:
      - "basic_lists0:Lists:TRUE:45"
      - "basic_formulas0:Formulas:TRUE:45"
      - "advanced_user_functions0:User-defined functions:TRUE:45"
      - "flow_control:Flow control (if/else, for):FALSE:30"
      - "basic_matrices0:Matrices:TRUE:15"
  slot6:
    slot_label : "Graphics"
    slot_date : 3
    slot_time : "09:00-12:00"
    slot_plan: "l40:b10:l40:b10:l30:b10:l40"
    lectures:
      - "ggplot_basics0:Plots/ggplot2:TRUE:40"
      - "ggplot_scales0:Plot axes/scales:TRUE:40"
      - "ggplot_facets_themes0:Plot panels/facets/size:TRUE:30"
      - "ggplot_geoms0:Plot types:FALSE:40"
  slot7:
    slot_label : "Data manipulation 3/3, self-study assignment"
    slot_date : 3
    slot_time : "13:15-17:00"
    slot_plan: "l90:b15:l90:b5:l25"
    lectures:
      - "dplyr_join0:Merging/joining tables:TRUE:45"
      - "tidyr_reshape0:Reshaping tables:TRUE:45"
      - "SSA:Self-study assignment:FALSE:90"
      - "QA:Q/A:FALSE:25"

#
# materials : material+
# material  : id:label:path:out_path "<id>:<label>:<>:<minutes>"
materials:
  - "pulse:Pulse dataset, CSV format:data/pulse.csv:data/pulse.csv"
  - "survey:Survey dataset, CSV format:data/survey.csv:data/survey.csv"
  - "exProjDir:RStudio project directory example:materials/RStudio_Project_Dir_Example.zip:materials/RStudio_Project_Dir_Example.zip"

#  - "SSA:Self-study assignment:data/ssa0.pdf:data/ssa0.pdf"
#  - "SSA_Solutions:Self-study assignment (solutions):data/ssa0_solutions.pdf:data/ssa0_solutions.pdf"
