---
title: "TODO notes"
output: html_document
---

# Tasks

## Ramin's

- (Ramin) d %>% filter( is.na( a_column ) ) => DONE!
- (Ramin) pull, distinct, rank => DONE except rank. We decided that rank and order are advanced topics. 
- (Ramin) top_n
- (Ramin) where is na.rm explained for the first time? 
    - (Szymon says) It is not explained yet!

## Szymon's

- (Bart or extra exercise) table, prop.table (for logistic regression)
- (Szymon) saveRDS, readRDS
- (Szymon) exercises ggplot::geom :
  - barplot with errors
  - show `geom_density` over histogram
  - `geom_smooth`: geom to show fit
  - geom to show function
- (Szymon) exercises formulas

## undecided

- set/get names() of vector elements
- `letters` and `LETTERS`; `pi`
- how to load a vector from file
- any, all
- some sections, for example forcats, has a different icon for info than the info_block function
		=> make sure that all sections use the same type of icons

## done

- (Szymon) replace x+3 with x in is.na paragraph in basic vectors. it is distracting.
- (Szymon) add format to all exercises after R Markdown introduced
- (Bart or extra exercise) `table` added, `prop.table` skipped (for logistic regression)
- (Szymon) exercises ggplot::scales
- (Szymon) exercises formulas

