---
title: "ggplot2 scales (practice)"
---

```{r , include=FALSE}
if (!is.null(knitr::opts_knit$get("solutions"))) {
  if (knitr::opts_knit$get("solutions")=="no") {
    knitr::opts_chunk$set(echo = FALSE, eval = FALSE, comment = NA, paged.print=FALSE)
  } else  {
    knitr::opts_chunk$set(echo = TRUE, eval = TRUE, comment = NA, paged.print=FALSE)
  }
} else {
    knitr::opts_chunk$set(echo = TRUE, eval = TRUE, comment = NA, paged.print=FALSE)
}

pulse <- read_pulse()
survey <- read_survey()
```


```{r, child="_exercises_format.Rmd",eval=TRUE,echo=FALSE} 
``` 

## Primary exercises

1. *Logarithmic scale and manual colors*.  
For the `pulse` data construct the plot shown below.  
Add `scale_x_log10` and `scale_y_log10` to change both location scales to logarithmic.  
Enforce the same `limits` from 50 to 150 on both scales.
```{r warning=FALSE,eval=TRUE}
ggplot( pulse ) +
  aes( x = pulse1, y = pulse2, color = ran ) +
  geom_point() +
  scale_x_log10( limits = c( 50, 150 ) ) + 
  scale_y_log10( limits = c( 50, 150 ) ) +
  xlab( "pulse1 (before exercise) [1/min]" ) +
  ylab( "pulse2 (after exercise) [1/min]" ) +
  scale_color_manual( values = c( ran = "black", sat = "orange" ) )
```

2.
scale fill color

## Extra exercises

scales::percent?
